### ISSUE TITLE
How to set continuous action

### ISSUE THREAD

**Issue by ZYunfeii** [tinyzqh/light_mappo#1]
I want to use continuous actions, but an error is reported after setting the `self.discrete_action_space` in the environment to false.

**Comment by Lumozz** [comment]
1.在env/env.py里把self.action_dim改为需要的值
2.在env/env_wrappers.py SubprocVecEnv中self.discrete_action_space改为False
3.env/env_wrappers.py中if len(total_action_space) > 1:判断里面的内容全删掉，加一句self.action_space.append(total_action_space[0])代替这个判度。
4.utils/act.py中，所有action_logits = self.action_out(x，available_actions)删去available_actions这个参数，因为连续动作空间不需要这个参数。
5.runner/shared或者separated/env_runner.py中collect方法，返回的参数中有一个actions_env，这是离散actions的one-hot编码形式，连续动作不需要one-hot，因此新加一个判度
`        elif self.envs.action_space[0].__class__.__name__ == "Box":
            actions_env = actions`
表示在连续动作空间时，action_envs=actions
6.结束
刚改完，现在能跑通，但是还有细看有没有其他的坑。

**Comment by tinyzqh** [comment]
在env_core.py之后，单独提出来了两个文件env_discrete.py和env_continuous.py这两个文件用于封装处理动作空间和离散动作空间。在algorithms/utils/act.py中elif self.continuous_action:这个判断逻辑也是用来处理连续动作空间的。和runner/shared/env_runner.py部分的# TODO 这里改造成自己环境需要的形式即可都是用来处理连续动作空间的。
